Preparing dataset...
Done
  0%|                                                                                             | 6/30000 [00:03<5:10:26,  1.61it/s]
Traceback (most recent call last):
  File "/home/hlwang/AVDC_change/flowdiffusion/pretrain.py", line 100, in <module>
    main(cfg)
  File "/home/hlwang/AVDC_change/flowdiffusion/pretrain.py", line 75, in main
    x, x_cond, goal, action = next(dl)
  File "/home/hlwang/AVDC_change/flowdiffusion/pretrain.py", line 24, in cycle
    for data in dl:
  File "/home/hlwang/miniconda3/envs/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "/home/hlwang/miniconda3/envs/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/hlwang/miniconda3/envs/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in __init__
    self._reset(loader, first_iter=True)
  File "/home/hlwang/miniconda3/envs/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1118, in _reset
    self._try_put_index()